name: CI (playwright)

# kích hoạt workflow khi có push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # sử dụng OS ubuntu-latest  để chạy job
    runs-on: ubuntu-latest
    # giới hạn thời gian chạy job là 30 phút
    timeout-minutes: 30
  
    steps:
      # B1: lấy code từ repository về
      - name: Pull code from repository (checkout)
        uses: actions/checkout@v4
      
      # B2: cài đặt Node.js (phiên bản 20.0.0 hoặc mới hơn)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      # B3: cài đặt các dependencies (library) của dự án
      - name: Install dependencies
        run: npm install

      # B4: tải browser (chromium) để chạy test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      # B4.1: Tạo file .env để lưu thông tin đăng nhập (nếu cần)
      - name: Create .env file
        run: |
          echo "USERNAME={{ secrets.USERNAME }}" >> .env
          echo "PASSWORD={{ secrets.PASSWORD }}" >> .env

      # B5: chạy test bằng Playwright
      - name: Run Playwright tests
        run: npx playwright test --project=chromium